// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TailorProTrack.infraestructure.Context;

#nullable disable

namespace TailorProTrack.infraestructure.Migrations
{
    [DbContext(typeof(TailorProTrackContext))]
    partial class TailorProTrackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TailorProTrack.domain.Entities.AccountCredit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("AMOUNT")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FK_BANK_ACC")
                        .HasColumnType("int");

                    b.Property<int>("FK_EXPENSE")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FK_BANK_ACC");

                    b.HasIndex("FK_EXPENSE");

                    b.ToTable("ACCOUNT_CREDIT");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.AccountDebit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("AMOUNT")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FK_BANK_ACC")
                        .HasColumnType("int");

                    b.Property<int?>("FK_PAYMENT")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FK_BANK_ACC");

                    b.HasIndex("FK_PAYMENT");

                    b.ToTable("ACCOUNT_DEBIT");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Bank", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("BANK");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.BankAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("BALANCE")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("BANK_ACCOUNT")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CREDIT_AMOUNT")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("DEBIT_AMOUNT")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("FK_BANK")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("BANK_ACCOUNT");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.BuyInventory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("COMPANY")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DATE_MADE")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NCF")
                        .HasColumnType("longtext");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RNC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TOTAL_SALE")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool?>("USED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("BUY_INVENTORY");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.BuyInventoryDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("COLOR_PRIMARY")
                        .HasColumnType("int");

                    b.Property<int>("COLOR_SECONDARY")
                        .HasColumnType("int");

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FK_BUY_INVENTORY")
                        .HasColumnType("int");

                    b.Property<int>("FK_PRODUCT")
                        .HasColumnType("int");

                    b.Property<int>("FK_SIZE")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PRICE")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("QUANTITY")
                        .HasColumnType("int");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("COLOR_PRIMARY");

                    b.HasIndex("COLOR_SECONDARY");

                    b.HasIndex("FK_BUY_INVENTORY");

                    b.HasIndex("FK_PRODUCT");

                    b.HasIndex("FK_SIZE");

                    b.ToTable("BUY_INVENTORY_DETAIL");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.CategorySize", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CATEGORY")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("CATEGORYSIZE");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DNI")
                        .HasColumnType("longtext");

                    b.Property<string>("FIRST_NAME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FIRST_SURNAME")
                        .HasColumnType("longtext");

                    b.Property<string>("LAST_NAME")
                        .HasColumnType("longtext");

                    b.Property<string>("LAST_SURNAME")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RNC")
                        .HasColumnType("longtext");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("CLIENT");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Color", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CODE_COLOR")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("COLORNAME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("COLOR");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Expenses", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("AMOUNT")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool?>("COMPLETED")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DESCR")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DOCUMENT_NUMBER")
                        .HasColumnType("longtext");

                    b.Property<int?>("FK_BUY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.Property<string>("VOUCHER")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("FK_BUY");

                    b.ToTable("EXPENSES");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Inventory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FK_PRODUCT")
                        .HasColumnType("int");

                    b.Property<int>("FK_SIZE")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("QUANTITY")
                        .HasColumnType("int");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("INVENTORY");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.InventoryColor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FK_COLOR_PRIMARY")
                        .HasColumnType("int");

                    b.Property<int?>("FK_COLOR_SECONDARY")
                        .HasColumnType("int");

                    b.Property<int>("FK_INVENTORY")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("QUANTITY")
                        .HasColumnType("int");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FK_INVENTORY");

                    b.ToTable("INVENTORY_COLOR");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.NoteCredit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("AMOUNT")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FK_CLIENT")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FK_CLIENT");

                    b.ToTable("NOTE_CREDIT");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.NoteCreditPayment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("AMOUNT")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FK_CREDIT")
                        .HasColumnType("int");

                    b.Property<int>("FK_PAYMENT")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PAYMENT_CREDIT_NOTE");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("AMOUNT")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("CHECKED")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DESCRIPTION_JOB")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FK_CLIENT")
                        .HasColumnType("int");

                    b.Property<int>("FK_PREORDER")
                        .HasColumnType("int");

                    b.Property<int>("FK_USER")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OBSERVATION")
                        .HasColumnType("longtext");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SEND_TO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("STATUS_ORDER")
                        .HasColumnType("longtext");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FK_CLIENT");

                    b.HasIndex("FK_PREORDER");

                    b.ToTable("ORDERS");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.OrderProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FK_INVENTORYCOLOR")
                        .HasColumnType("int");

                    b.Property<int>("FK_ORDER")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("QUANTITY")
                        .HasColumnType("int");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FK_INVENTORYCOLOR");

                    b.HasIndex("FK_ORDER");

                    b.ToTable("ORDER_PRODUCTS");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Payment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ACCOUNT_NUMBER")
                        .HasColumnType("longtext");

                    b.Property<string>("ACCOUNT_PAYMENT")
                        .HasColumnType("longtext");

                    b.Property<decimal>("AMOUNT")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FK_BANK_ACCOUNT")
                        .HasColumnType("int");

                    b.Property<int>("FK_ORDER")
                        .HasColumnType("int");

                    b.Property<int>("FK_TYPE_PAYMENT")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("NOTE_CREDIT")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PAYMENT");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.PaymentExpenses", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("AMOUNT")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FK_BANK_ACCOUNT")
                        .HasColumnType("int");

                    b.Property<int>("FK_EXPENSE")
                        .HasColumnType("int");

                    b.Property<int>("FK_PAYMENT_TYPE")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FK_BANK_ACCOUNT");

                    b.HasIndex("FK_EXPENSE");

                    b.HasIndex("FK_PAYMENT_TYPE");

                    b.ToTable("PAYMENT_EXPENSES");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.PaymentType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TYPE_PAYMENT")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PAYMENT_TYPE");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Phone", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FK_CLIENT")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NUMBER")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TYPE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PHONE");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.PreOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool?>("COMPLETED")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DATE_DELIVERY")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("FINISHED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("FK_CLIENT")
                        .HasColumnType("int");

                    b.Property<bool?>("ITBIS")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FK_CLIENT");

                    b.ToTable("PRE_ORDER");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.PreOrderProducts", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("COLOR_PRIMARY")
                        .HasColumnType("int");

                    b.Property<int?>("COLOR_SECONDARY")
                        .HasColumnType("int");

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("CUSTOM_PRICE")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("FK_PREORDER")
                        .HasColumnType("int");

                    b.Property<int>("FK_PRODUCT")
                        .HasColumnType("int");

                    b.Property<int>("FK_SIZE")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("QUANTITY")
                        .HasColumnType("int");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("COLOR_PRIMARY");

                    b.HasIndex("COLOR_SECONDARY");

                    b.HasIndex("FK_PREORDER");

                    b.HasIndex("FK_PRODUCT");

                    b.HasIndex("FK_SIZE");

                    b.ToTable("PRE_ORDER_PRODUCTS");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DESCRIPTION_PRODUCT")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FK_TYPE")
                        .HasColumnType("int");

                    b.Property<DateTime>("LAST_REPLENISHMENT")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NAME_PRODUCT")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("SALE_PRICE")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FK_TYPE");

                    b.ToTable("PRODUCT");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.ProductColor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FK_COLOR")
                        .HasColumnType("int");

                    b.Property<int>("FK_PRODUCT")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FK_COLOR");

                    b.HasIndex("FK_PRODUCT");

                    b.ToTable("PRODUCTS_COLOR");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.ProductSize", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FK_PRODUCT")
                        .HasColumnType("int");

                    b.Property<int>("FK_SIZE")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FK_PRODUCT");

                    b.HasIndex("FK_SIZE");

                    b.ToTable("PRODUCTS_SIZE");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Sales", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("B14")
                        .HasColumnType("longtext");

                    b.Property<string>("COD_ISC")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FK_PREORDER")
                        .HasColumnType("int");

                    b.Property<bool?>("INVOICED")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("ITBIS")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("TOTAL_AMOUNT")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FK_PREORDER");

                    b.ToTable("SALES");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Size", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FKCATEGORYSIZE")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SIZE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FKCATEGORYSIZE");

                    b.ToTable("SIZE");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Supplier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NAME_SUPPLIER")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RNC")
                        .HasColumnType("longtext");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("SUPPLIERS");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Type_prod", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("REMOVED")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TYPE_PROD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("USER_CREATED")
                        .HasColumnType("int");

                    b.Property<int?>("USER_MOD")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("TYPE_PROD");
                });

            modelBuilder.Entity("TailorProTrack.domain.Reports.MissedInventory", b =>
                {
                    b.Property<int>("CantidadFaltante")
                        .HasColumnType("int");

                    b.Property<string>("ColorPrimary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ColorSecondary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("MissedInv");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.AccountCredit", b =>
                {
                    b.HasOne("TailorProTrack.domain.Entities.BankAccount", "BankAccount")
                        .WithMany("AccountCredit")
                        .HasForeignKey("FK_BANK_ACC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorProTrack.domain.Entities.Expenses", "Expense")
                        .WithMany("AccountCredit")
                        .HasForeignKey("FK_EXPENSE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.AccountDebit", b =>
                {
                    b.HasOne("TailorProTrack.domain.Entities.BankAccount", "BankAccount")
                        .WithMany("AccountDebit")
                        .HasForeignKey("FK_BANK_ACC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorProTrack.domain.Entities.Payment", "Payment")
                        .WithMany("AccountDebit")
                        .HasForeignKey("FK_PAYMENT");

                    b.Navigation("BankAccount");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.BuyInventoryDetail", b =>
                {
                    b.HasOne("TailorProTrack.domain.Entities.Color", "ColorPrimary")
                        .WithMany("ColorPrimaryInBuys")
                        .HasForeignKey("COLOR_PRIMARY")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorProTrack.domain.Entities.Color", "ColorSecondary")
                        .WithMany("ColorSecondaryInBuys")
                        .HasForeignKey("COLOR_SECONDARY")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorProTrack.domain.Entities.BuyInventory", "BuyInventory")
                        .WithMany("Details")
                        .HasForeignKey("FK_BUY_INVENTORY")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorProTrack.domain.Entities.Product", "Product")
                        .WithMany("productsInBuys")
                        .HasForeignKey("FK_PRODUCT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorProTrack.domain.Entities.Size", "Size")
                        .WithMany("sizeInBuys")
                        .HasForeignKey("FK_SIZE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyInventory");

                    b.Navigation("ColorPrimary");

                    b.Navigation("ColorSecondary");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Expenses", b =>
                {
                    b.HasOne("TailorProTrack.domain.Entities.BuyInventory", "BuyInventory")
                        .WithMany("Expenses")
                        .HasForeignKey("FK_BUY");

                    b.Navigation("BuyInventory");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.InventoryColor", b =>
                {
                    b.HasOne("TailorProTrack.domain.Entities.Inventory", "Inventory")
                        .WithMany("InventoryColor")
                        .HasForeignKey("FK_INVENTORY")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.NoteCredit", b =>
                {
                    b.HasOne("TailorProTrack.domain.Entities.Client", "Client")
                        .WithMany("NoteCredit")
                        .HasForeignKey("FK_CLIENT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Order", b =>
                {
                    b.HasOne("TailorProTrack.domain.Entities.Client", "Client")
                        .WithMany("Order")
                        .HasForeignKey("FK_CLIENT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorProTrack.domain.Entities.PreOrder", "PreOrder")
                        .WithMany("Order")
                        .HasForeignKey("FK_PREORDER")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("PreOrder");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.OrderProduct", b =>
                {
                    b.HasOne("TailorProTrack.domain.Entities.InventoryColor", "InventoryColor")
                        .WithMany("OrderProducts")
                        .HasForeignKey("FK_INVENTORYCOLOR")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorProTrack.domain.Entities.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("FK_ORDER")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryColor");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.PaymentExpenses", b =>
                {
                    b.HasOne("TailorProTrack.domain.Entities.BankAccount", "BankAccount")
                        .WithMany("PaymentExpenses")
                        .HasForeignKey("FK_BANK_ACCOUNT");

                    b.HasOne("TailorProTrack.domain.Entities.Expenses", "Expense")
                        .WithMany("PaymentsExpenses")
                        .HasForeignKey("FK_EXPENSE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorProTrack.domain.Entities.PaymentType", "PaymentType")
                        .WithMany("PaymentExpensesList")
                        .HasForeignKey("FK_PAYMENT_TYPE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");

                    b.Navigation("Expense");

                    b.Navigation("PaymentType");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.PreOrder", b =>
                {
                    b.HasOne("TailorProTrack.domain.Entities.Client", "Client")
                        .WithMany("PreOrder")
                        .HasForeignKey("FK_CLIENT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.PreOrderProducts", b =>
                {
                    b.HasOne("TailorProTrack.domain.Entities.Color", "ColorPrimary")
                        .WithMany("ColorPrimaryInPreOrder")
                        .HasForeignKey("COLOR_PRIMARY")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorProTrack.domain.Entities.Color", "ColorSecondary")
                        .WithMany("ColorSecondaryInPreOrder")
                        .HasForeignKey("COLOR_SECONDARY");

                    b.HasOne("TailorProTrack.domain.Entities.PreOrder", "PreOrder")
                        .WithMany("PreOrderProducts")
                        .HasForeignKey("FK_PREORDER")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorProTrack.domain.Entities.Product", "Product")
                        .WithMany("PreOrderProducts")
                        .HasForeignKey("FK_PRODUCT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorProTrack.domain.Entities.Size", "Size")
                        .WithMany("PreOrderProducts")
                        .HasForeignKey("FK_SIZE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColorPrimary");

                    b.Navigation("ColorSecondary");

                    b.Navigation("PreOrder");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Product", b =>
                {
                    b.HasOne("TailorProTrack.domain.Entities.Type_prod", "Type")
                        .WithMany("Products")
                        .HasForeignKey("FK_TYPE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.ProductColor", b =>
                {
                    b.HasOne("TailorProTrack.domain.Entities.Color", "Color")
                        .WithMany("ProductColor")
                        .HasForeignKey("FK_COLOR")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorProTrack.domain.Entities.Product", "Product")
                        .WithMany("ProductColors")
                        .HasForeignKey("FK_PRODUCT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.ProductSize", b =>
                {
                    b.HasOne("TailorProTrack.domain.Entities.Product", "Product")
                        .WithMany("ProductSizes")
                        .HasForeignKey("FK_PRODUCT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TailorProTrack.domain.Entities.Size", "Size")
                        .WithMany("ProductSize")
                        .HasForeignKey("FK_SIZE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Sales", b =>
                {
                    b.HasOne("TailorProTrack.domain.Entities.PreOrder", "PreOrder")
                        .WithMany("Sale")
                        .HasForeignKey("FK_PREORDER")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreOrder");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Size", b =>
                {
                    b.HasOne("TailorProTrack.domain.Entities.CategorySize", "categorySize")
                        .WithMany()
                        .HasForeignKey("FKCATEGORYSIZE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categorySize");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.BankAccount", b =>
                {
                    b.Navigation("AccountCredit");

                    b.Navigation("AccountDebit");

                    b.Navigation("PaymentExpenses");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.BuyInventory", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Client", b =>
                {
                    b.Navigation("NoteCredit");

                    b.Navigation("Order");

                    b.Navigation("PreOrder");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Color", b =>
                {
                    b.Navigation("ColorPrimaryInBuys");

                    b.Navigation("ColorPrimaryInPreOrder");

                    b.Navigation("ColorSecondaryInBuys");

                    b.Navigation("ColorSecondaryInPreOrder");

                    b.Navigation("ProductColor");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Expenses", b =>
                {
                    b.Navigation("AccountCredit");

                    b.Navigation("PaymentsExpenses");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Inventory", b =>
                {
                    b.Navigation("InventoryColor");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.InventoryColor", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Payment", b =>
                {
                    b.Navigation("AccountDebit");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.PaymentType", b =>
                {
                    b.Navigation("PaymentExpensesList");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.PreOrder", b =>
                {
                    b.Navigation("Order");

                    b.Navigation("PreOrderProducts");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Product", b =>
                {
                    b.Navigation("PreOrderProducts");

                    b.Navigation("ProductColors");

                    b.Navigation("ProductSizes");

                    b.Navigation("productsInBuys");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Size", b =>
                {
                    b.Navigation("PreOrderProducts");

                    b.Navigation("ProductSize");

                    b.Navigation("sizeInBuys");
                });

            modelBuilder.Entity("TailorProTrack.domain.Entities.Type_prod", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
